languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "哈希说"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "Web3世界的内容雷达，教程 / 空投 / 周报 / 热榜 / 工具，一站搞定"

[params.author]
  name = "哈希说"
  image = "img/blowfish_logo.png"
  headline = "Web3世界的内容雷达，教程 / 空投 / 周报 / 热榜 / 工具，一站搞定"
  bio = "Web3世界的内容雷达，教程 / 空投 / 周报 / 热榜 / 工具，一站搞定"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]