[[main]]
name = "空投聚合"
pageRef = "airdrops"
weight = 1

[[main]]
name = "钱包追踪"
pageRef = "wallets"
weight = 2


[[main]]
name = "数据榜单"
pageRef = "rankings"
weight = 3

[[main]]
name = "技术周报"
pageRef = "weekly"
weight = 4

[[main]]
name = "工具导航"
pageRef = "tools"
weight = 5

[[main]]
parent = "更多"
name = "项目解析"
pageRef = "projects"
weight = 6

[[main]]
parent = "更多"
name = "学习教程"
pageRef = "tutorials"
weight = 7

[[main]]
parent = "更多"
name = "订阅入口"
pageRef = "subscribe"
weight = 8


[[main]]
parent = "更多"
name = "招聘信息"
pageRef = "jobs"
weight = 9


[[main]]
identifier = "twitter"
pre = "x-twitter"
url = "https://twitter.com/biturd"
weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/bit-urd"
weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Authors"
pageRef = "authors"
weight = 20
