baseURL = "https://web3biturd.com/"
languageCode = "zh-cn"
title = "Web3 Station"
theme = "stack"

[params]
  mainSections = ["airdrops", "wallets", "projects", "rankings", "weekly", "guides", "tools", "jobs"]
  description = "Web3 Station 是一个聚合 Web3 空投机会、链上数据、项目解析、钱包追踪与招聘信息的每日更新站点。"

# 新的写法（✅正确）
[pagination]
  pagerSize = 10
  path = "page"

[menu]

  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "空投聚合"
    url = "/airdrops/"
    weight = 2

  [[menu.main]]
    name = "钱包追踪"
    url = "/wallets/"
    weight = 3

  [[menu.main]]
    name = "项目解析"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "数据榜单"
    url = "/rankings/"
    weight = 5

  [[menu.main]]
    name = "技术周报"
    url = "/weekly/"
    weight = 6

  [[menu.main]]
    name = "学习教程"
    url = "/guides/"
    weight = 7

  [[menu.main]]
    name = "工具导航"
    url = "/tools/"
    weight = 8

  [[menu.main]]
    name = "招聘信息"
    url = "/jobs/"
    weight = 9

  [[menu.main]]
    name = "订阅入口"
    url = "/subscribe/"
    weight = 10

